project:
  type: website
  preview:
    port: 8080
    browser: false

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "Blog Pessoal"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/guilherme-loiola-fernandes

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



